### ISSUE TITLE
ActiveAdmin 3 support

### ISSUE THREAD

**Issue by Fs00** [blocknotes/activeadmin_blaze_theme#29]
The gem currently has a requirement on ActiveAdmin 2.x, which causes the inability to upgrade to AA 3.
I don't know if the requirement can simply be lifted or there are some changes to do, but it would be nice to have AA 3 support too.

**Comment by kusihed75** [comment]
Hi everybody

when I change the line 27 in the gemspec file to

`spec.add_runtime_dependency 'activeadmin', '> 2.0'`

and load it locally in the gemfile (`gem 'activeadmin_blaze_theme', path: './lib/activeadmin_blaze_theme'`)

then things seem to work just fine.

So that change should allow activeadmin_blaze_theme to work with AA3...

What do you think about that change request?

**Comment by kusihed75** [comment]
By the way, the fork https://github.com/glebtv/activeadmin_blaze_theme already did this update for AA3.. Are you willing to that as well in this repository at all?

**Comment by blocknotes** [comment]
Thanks for the issue @Fs00 - I have just updated the ActiveAdmin version range to support 3.x

**Comment by Fs00** [comment]
Thank you!
